# Generated by Django 5.0.6 on 2024-05-29 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_enquiry_delete_contactinformation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enquiry',
            new_name='contact',
        ),
    ]
