# Generated by Django 5.0.6 on 2024-05-29 13:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_rename_enquiry_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
